version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "${CLIENT_PORT}:8000"
    environment:
      - VITE_API_URL=http://${SERVER_HOST}:${SERVER_PORT}
    volumes:
      - type: bind
        source: ./client
        target: /app
    stdin_open: true
    tty: true
    depends_on:
      - server
      
  server:
    build: ./server
    ports:
      - "${SERVER_PORT}:5000"
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - type: bind
        source: ./server
        target: /app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  postgres_data:
