version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "${CLIENT_PORT}:80"
    volumes:
      - ./my-react-app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
      
  server:
    build: ./server
    ports:
      - "${SERVER_PORT}:5000"
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
